greywolfx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("staticpages.urls"))
]

staticpages/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'staticpages'

urlpatterns = [
    path("", views.index, name="index"),
    path("contact", views.contact, name="contact"),
    path("terms", views.term_conditions, name="term_conditions"),
    path("privacy", views.privacy_policy, name="privacy_policy"),
    path("services", views.services, name="services"),
    path("about", views.about, name="about"),
    path("login", auth_views.LoginView.as_view(), name="login"),
    path("signup", views.signup, name="signup"),
    path("blog_list", views.blog_list, name="blog_list"),
    path("blog/<int:pk>/", views.blog_details, name="blog_detail"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("profile", views.ProfileView, name="profile"),
    path("category/<int:id>/", views.category_items, name="category_items")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staticpages/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Comment, Profile, Subscribe

class signupForm(forms.ModelForm):
    """Form definition for signup."""
    password1 = forms.CharField(widget = forms.PasswordInput(attrs={"class":"form-control", "placeholder":"enter your password"}))
    password2 = forms.CharField(widget = forms.PasswordInput(attrs={"class":"form-control", "placeholder":"enter your password"}))
    
    class Meta:
        """Meta definition for signupform."""

        model = User
        fields = ('username', 'email', 'password1', 'password2')
        labels = {
            "username": "Username",
            "email": "email",
            "password1": "password",
            "password2": "confirm_password",
        }
        
    def clean_password(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        username = self.cleaned_password.get("username")
        
        if password1 and password2 and password1 == password2:
            return form.ValidationError("password1 and password 2 are not the same")
            if len(password1) <= 10 and len(password2) <= 10:
                return forms.ValidationError("Password length should be 10 or more characters")
                if password1 and password2 and username and username in password1 :
                    return forms.ValidationError("you can not use the username as your password")        
        return password1
    
    def strong_pass(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        password = password1 and password2
        special_characters = ("@" "#", "$","%","&","*","(",")", "!")
        
        if password and any(char in special_characters for char in password):
            return forms.ValidationError("Password should contain at least one special character")
        return password1
    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")

        return email
    
    def clean_username(self):
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already exists")
        return username

class commentsForm(forms.ModelForm):
    """Form definition for Comment."""

    class Meta:
        """Meta definition for commentsform."""

        model = Comment
        fields = ("content", "parent")
        labels = {
            "content": "comment",
        }
        widgets = {
            "content": forms.Textarea(attrs={"class":"form-control", 'rows':2}),
            "parent": forms.HiddenInput(),
        }
        
    def clean_comment(self):
        content = self.cleaned_data.get("content")
        if content == content:
            return forms.ValidationError("the same comment can not be returned")
        return content
    
class UserProfileForm(forms.ModelForm):
    """Form definition for UserProfile."""

    class Meta:
        """Meta definition for UserProfileform."""

        model = Profile
        fields = ('profile_picture', 'bio')
        
        widgets = {
            "profile_picture": forms.ClearableFileInput(attrs={"class":"form-control"}),
            "bio": forms.Textarea(attrs={"class":"form-control", "placeholder":"Limited by only our imagination", "size":5}),
        }


class ProfileForm(forms.ModelForm):   
    class Meta: 
        model = User 
        fields = ['username','first_name', 'last_name', 'email'] 
        labels = { 
            'username':'Username', 
            'first_name': 'First Name', 
            'last_name': 'Last Name', 
            'email': 'Email', 
        } 

        widgets = { 
            'username': forms.TextInput(attrs={'class':'form-control'}), 
            'first_name': forms.TextInput(attrs={'class':'form-control'}), 
            'last_name':forms.TextInput(attrs={'class':'form-control'}), 
            'email': forms.TextInput(attrs={'class':'form-control'}), 
        }
        
    def clean_username(self):
        username = self.cleaned_data.get("username")
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")
            
        if username and first_name and last_name and username == first_name or username == last_name:
            return forms.ValidationError("username can not be the same as first name or last name")
        return username
    
    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
        return email 
    
    def clean_first_name(self):
        first_name = self.cleaned_data.get("first_name")
        if first_name and first_name.isalpha() == False:
            raise forms.ValidationError("First name should contain only alphabets")
        return first_name
    
    def clean_last_name(self):
        last_name = self.cleaned_data.get("last_name")
        if last_name and last_name.isalpha() == False:
            raise forms.ValidationError("Last name should contain only alphabets")
        return last_name
    

class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribe
        fields = ['email']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'})
        }
        
    def clean_email(self):
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError("Email already exists")
            if email and Subscribe.objects.filter(email=email).exists():
                raise forms.ValidationError("Email already subscribed")
        return email

staticpages/views.py
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import signupForm, commentsForm, ProfileForm, UserProfileForm, SubscribeForm
from .models import BlogPost, Comment, Profile, Category, Subscribe, Testimonial
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from datetime import timedelta
from django.views.generic import DetailView
from django.utils import timezone
from django.db.models import Count


# Create your views here.
def index(request):
    return render(request, "staticpages/index.html")

def about(request):
    return render(request, "staticpages/about.html")

def contact(request):
    return render(request, "staticpages/contact.html")

def privacy_policy(request):
    return render(request, "staticpages/privacy_policy.html")

def services(request):
    return render(request, "staticpages/services.html")

def term_conditions(request):
    return render(request, "staticpages/term_conditions.html")

def signup(request):
    if request.method == "POST":
        form = signupForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            if User.objects.filter(email=email).exists():
                messages.error(request, "user with the email already exist")
                return HttpResponseRedirect(reverse("staticpages:signup"))
            user = form.save(commit=False)
            user.set_password(form.cleaned_data["password1"])
            user.save()
            
            messages.success(request, "Registration successful")
            login(request, user)
            return HttpResponseRedirect(reverse("staticpages:signup"))
        else:
            messages.error(request, "invalid form")
            return HttpResponseRedirect(reverse("staticpages:signup"))
    else:
        form = signupForm()
    context = {'form':form}
    return render(request, "registration/signup.html", context)

def blog_list(request):
    posts = BlogPost.objects.all().order_by('-time_uploaded')

    
    paginator = Paginator(posts, 12)  # Show 12 blogs per page.

    url = reverse('staticpages:blog_list')
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj, 'url':url,}
    return render(request, "staticpages/blog.html", context)

@login_required
def blog_details(request, pk):
    try:
        post = get_object_or_404(BlogPost, pk=pk)
        comments = post.comments.filter(parent__isnull=True)
        new_comment = None
        
        form = commentsForm()
        subscribe_form = SubscribeForm()
        
        if request.method == "POST":
            if 'comment_submit' in request.POST:
                comment_form = commentsForm(request.POST)
                if comment_form.is_valid():
                    new_comment = comments_form.save(commit=False)
                    new_comment.user = request.user
                    new_comment.profile = request.user.profile
                    new_comment.post = post
                    new_comment.save()
                    form = commentsForm()
                    return HttpResponseRedirect(reverse('staticpages:blog_detail', args=[pk]))
                else:
                    messages.error(request, "Invalid comment form")
            elif 'subscribe_submit' in request.POST:
                subscribe_form = SubscribeForm(request.POST)
                if subscribe_form.is_valid():
                    subscribe_form.save()
                    messages.success(request, "You have successfully subscribed!")
                else:
                    messages.error(request, "Invalid email for subscription")
            
            return HttpResponseRedirect(reverse("staticpages:blog_detail", args=[pk]))
        
        now = timezone.now()
        one_week_ago = now - timedelta(days=7)
        
        top_stories = BlogPost.objects.filter(time_uploaded__gte=one_week_ago).order_by('-likes')[:3]
        
        context = {
            "title": "blog_detail",
            "form": form,
            "subscribe_form": subscribe_form,
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "top_stories": top_stories,
        }
        return render(request, "staticpages/single.html", context)
    
    except BlogPost.DoesNotExist:
        return HttpResponse("Blog does not exist", status=404)

def category_items(request, id):
    category = get_object_or_404(Category, id=id)
    category_posts = BlogPost.objects.filter(category=category)
    context = {"title":"category_items", "category":category, "category_posts":category_posts}
    return render(request, "staticpages/category_items.html", context)
    
@login_required   
def ProfileView(request):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST, instance=request.user)
        profile, created = Profile.objects.get_or_create(user=request.user)
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
    
        if form.is_valid():
            profile_form.save()
            form_save()
            
            messages.success(request, "profile updated successful")
            return HttpResponseRedirect(reverse("staticpages:profile"))
        else:
            return HttpResponseRedirect(reverse("staticpages:profile"))
    else:
        profile_form = ProfileForm(instance=request.user)
        profile, created = Profile.objects.get_or_create(user=request.user)
        form = UserProfileForm(instance=profile)
    context = {"title":"profile", "form":form, "profile":profile, "profile_form":profile_form}
    return render(request, "staticpages/profile.html", context)

@login_required
def Employeeview(request):
    pass
    

staticpages/templates/staticpages/tags/category_list.html
<div class="tech-btm">
    <h4>Categories</h4>
    <ul class="list-group single">
        {% for category in categories %}
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <a href="{% url 'staticpages:category_items' category.id %}">{{ category.name }}</a>
                <span class="badge badge-primary badge-pill">{{ category.posts.count }}</span>
            </li>
        {% endfor %} 
       
    </ul>
</div>

staticpages/templates/staticpages/tags/director.html
<section class="team pt-5">
	<div class="container py-md-5 py-3">
		<h3 class="heading mb-md-5 mb-4">Our <strong>Team Professionals</strong></h3>
		<div class="row">
			<div class="col-lg-4">
				<div class="blog-info">
					<h4 class="heading mt-lg-2">Meet Our Experts</h4>
					<p class="mt-sm-3 mt-2">Our team of professionals is dedicated to advancing AI technology and delivering innovative solutions that drive success for our clients.</p>
				</div>
			</div>
			<div class="col-lg-8 text-center mt-lg-0 mt-4">
				<div class="row">
                    
                    {% if directors %}
                        
                        {% for director in directors %}
                            <div class="col-md-4 col-6 item" >
                                <div class="clients-color">
                                <div class="w3-w3pvt-team-img">
                                    <img src="{{ director.director_picture.url }}" class="img-fluid img-thumbnail"
                                    alt="{{ director.director_name }}" style="max-height: 200px;">
                                </div>
                                <div class="team-txt-info pt-3">
                                    <h4>{{ director.director_name }}</h4>
                                    <p class="mb-3">{{ director.director_post }}</p>
                                </div>
                                </div>
                            </div>
                        {% endfor %}
                            
                    {% else %}
                        no directors available right now 
                    {% endif %}
                        
				   
				</div>
			</div>
		</div>
	</div>
</section>

staticpages/templates/staticpages/tags/testimonial.html
<section class="clients">
	<div class="layer py-lg-5 py-lg-4">
		<div class="container py-5">
			<h2 class="heading mb-md-5 mb-4">Our <strong>Customers' Feedback</strong></h2>
                <div class="row">
                    {% for testimonial in testimonials %}
                    <div class="col-lg-4 col-md-6 pl-sm-0 mb-4">
                        <div class="col- client-grid grid flex-fill" style="border-radius: 7px; overflow: hidden;">
                            <div class="c-left" >
                                <img src="{{ testimonial.picture.url }}" alt="Customer Feedback" class="img-fluid" />
                                <div class="info">
                                    <h6>{{ testimonial.name }}</h6>
                                    <p>- {{ testimonial.post }}</p>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                                <p class="mt-2">{{ testimonial.feedback }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
		</div>
	</div>
</section>